version: '3'
services:
  app:
    ports:
      - "8000:80"
    build: ./docker
    container_name: laravel_post_app
    environment:
      - VIRTUAL_HOST=post.laravel.com
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:5.7
    container_name: laravel_post_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/env/my.cnf:/etc/mysql/conf.d/my.cnf
      - laravel_post_db_data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  laravel_post_db_data:

